export const tickerData = [
  {
    name: 'aaa',
    symbol: 'AAA',
    url: 'https://example.com/ticker/aaa',
    country: 'country 1',
    industry: 'industry 1',
    market: 'market 1',
    sector: 'sector 1',
    price: 120,
    quantity: '2',
  },
  {
    name: 'bbb',
    symbol: 'BBB',
    url: 'https://example.com/ticker/bbb',
    country: 'country 1',
    industry: 'industry 1',
    market: 'market 2',
    sector: 'sector 2',
    price: 94,
    quantity: '2',
  },
  {
    name: 'ccc',
    symbol: 'CCC',
    url: 'https://example.com/ticker/ccc',
    country: 'country 2',
    industry: 'industry 1',
    market: 'market 1',
    sector: 'sector 2',
    price: 35,
    quantity: '10',
  },
  {
    name: 'ddd',
    symbol: 'DDD',
    url: 'https://example.com/ticker/ddd',
    country: 'country 2',
    industry: 'industry 1',
    market: 'market 2',
    sector: 'sector 1',
    price: 84,
    quantity: '12',
  },
];
