name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 'lts'
          registry-url: https://npm.pkg.github.com/
      - run: npm install --frozen-lockfile
      - run: npm run test
