name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4.3.0
        with:
          node-version: 'lts/23.10'
      - run: npm install --frozen-lockfile
      - run: npm run test
